accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup")
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('receipts/', include('receipts.urls')),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("home")))
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    AccountCreateView,
    ExpenseCategoryCreateView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="receipt_account_create",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="receipt_category_create",
    ),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="receipt_category_list",
    ),
    path("accounts/", AccountListView.as_view(), name="receipt_account_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(default=timezone.now)
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password1']
            user = User.objects.create_user(username, password=password)
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from receipts.models import Account, Receipt, ExpenseCategory
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("receipt_account_list")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/expense_category_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("receipt_category_list")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_category_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Receipts</title>
</head>
<style>
    li {
      display: inline;
      padding : 0;
      margin : 0 0 0 12px; 
      font-size: small;
   }
  </style>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                <li><a href="{%url 'home' %}">Receipts</a></li>
                <li><a href="{% url 'receipt_category_list' %}">Expense Category</a></li>
                <li><a href="{% url 'receipt_account_list' %}">Account</a></li>
                <li><a href="{% url 'receipt_category_create' %}">Create Expense Category</a></li>
                <li><a href="{% url 'receipt_create' %}">Create Receipts</a></li>
                <li><a href="{% url 'receipt_account_create' %}">Create Account</a></li>
                {%else%}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/receipts/account_create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create Account</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}

{%block content%}
<h1>Account</h1>
<table class="table table-bordered table-striped table-condensed table-hover">
    <thead> 
        <tr>
            <th> Name </th>
            <th> Number </th>
            <th> Number of receipts</th>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td> {{account.name}} </td>
            <td>{{account.number}}</td>
            <td>{{account|length}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%endblock content%}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/expense_category_create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create Expense</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/expense_category_list.html
{% extends 'base.html' %}

{%block content%}
<h1>Expense Category</h1>
<table class="table table-bordered table-striped table-condensed table-hover">
    <thead> 
        <tr>
            <th> Name </th>
            <th> Number of receipts </th>
    </thead>
    <tbody>
        {% for expensecategory in expensecategory_list %}
        <tr>
            <td> {{expensecategory.name}} </td>
            <td>{{expensecategory|length}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%endblock content%}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{%block content%}
<h1>Receipts</h1>
<table class="table table-bordered table-striped table-condensed table-hover">
    <thead class="thead-dark">
        <tr>
            <th> Vendor </th>
            <th> Total </th>
            <th> Tax </th>
            <th> Date </th>
            <th> Category </th>
            <th> Account </th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td> {{receipt.vendor}} </td>
            <td> {{receipt.total}} </td>
            <td> {{receipt.tax}} </td>
            <td> {{receipt.date}} </td>
            <td> {{receipt.category}} </td>
            <td>{{receipt.account|default_if_none:"Cash"}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%endblock content%}